name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  nix:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            system: x86_64-linux
          - runner: macos-latest
            system: aarch64-darwin
          - runner: ubuntu-24.04-arm
            system: aarch64-linux
    runs-on: ${{ matrix.runner }}
    name: nix flake check (${{ matrix.system }})
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
        with:
          nix_conf: extra-experimental-features = nix-command flakes ca-derivations impure-derivations
      - run: nix flake check --print-build-logs --no-update-lock-file --impure
